### PR TITLE
Adjusted kbsearch implementation - refactoring

### PR DESCRIPTION
**Pull request by tomas-knap**
I did some adjustments to kbsearch. Please test that. 

What is missing: 
1) Why are the methods findEntityX implemented in DBpediaSearch and not in SparqlSearch? There are couple of customizations regarding the predicate names, but this can be extracted to the config file e.g. because they are for sure not DBpedia specific and they do not justify creation of new class. **Solution:** Please adjust it in a way that there is no need to define DBPedia* classes but rather it is enough to use standard SPARQL* classes (logic from DBPediaSearch is moved to SparqlSearch etc.). The configurations of predicates etc. can go to the config file and can always configure the SparqlSearch class - many of these config params will be the same for different sparql repositories. 
2) Certain logic is repeated - DbpediaSearch - 
findEntityCandidatesOfTypes and findEntityCandidates. Anytime couple of rows of code are repeated, this is a source of error and confusion as the time goes - so please remove the repeated code in DbpediaSearch.

Please put the changes here to this branch. When you are done, before merging, please assign to me, I will briefly look on it.

### CODE REVIEW

**Comment by tomas-knap** [comment]
@brodecva FYI

**Comment by brodecva** [comment]
@tomas-knap As @JanVana has just left us for a week, I will deal with this. The instructions seem clear to me. Thanks!

**Comment by brodecva** [comment]
Everything apart the "move DBpedia specific enums to configuration" part is done. The reason is that I have fundamental objections to the way the resources, classes, entities and the likes are treated and I am not sure that this change would really make the difference. I will explain later.
Anyway please check the changes.

**Comment by brodecva** [comment]
A clean cache might be needed to run the conversion without errors.

**Comment by brodecva** [comment]
As the "move DBpedia specific enums to configuration" will go nicely with other configuration related issues @JanVana is tasked with and I really have to focus on other non-KB related issues, I will assign this final tidbit to him. Hope he won't mind.

**Comment by brodecva** [comment]
We have decided to merge this branch in the current state to develop. Jan will make the change mentioned above in his own branch.

**Pull request merged**
